"""
Comprehensive AHTN/HS chapter hints for product classification.

Maps product keywords to HS chapters (2 digits) or headings (4 digits).
Order matters: more specific hints (HEADING_HINTS) are checked first.
Based on WCO Harmonized System structure.
"""

# ─────────────────────────────────────────────────────────────────────────────
# Heading-level hints (4 digits) — most specific, checked first
# Use when chapter alone is ambiguous (e.g. rubber gloves vs rubber latex)
# ─────────────────────────────────────────────────────────────────────────────
HEADING_HINTS: dict[tuple[str, str], str] = {
    # Rubber gloves, mittens, mitts
    ("rubber", "glove"): "4015",
    ("disposable", "glove"): "4015",
    ("latex", "glove"): "4015",
    ("nitrile", "glove"): "4015",
    # Handbags, travel goods
    ("handbag", "leather"): "4202",
    ("handbag", "bag"): "4202",
    ("travel", "bag"): "4202",
    ("suitcase", "luggage"): "4202",
    # Footwear
    ("leather", "shoe"): "6403",
    ("sports", "shoe"): "6404",
    ("rubber", "shoe"): "6404",
    # Machinery
    ("computer", "laptop"): "8471",
    ("computer", "desktop"): "8471",
    ("mobile", "phone"): "8517",
    ("smartphone", "phone"): "8517",
    # Cocoa/chocolate
    ("chocolate", "cocoa"): "1806",
    ("chocolate", "bar"): "1806",
    ("cocoa", "powder"): "1805",
    # Chocolate-coated biscuits → biscuits (Ch 19), not chocolate (Ch 18)
    ("chocolate", "biscuit"): "1905",
    ("chocolate", "cookie"): "1905",
    # Pharmaceutical
    ("medicine", "pharmaceutical"): "3004",
    ("drug", "pharmaceutical"): "3004",
    ("vaccine", "pharmaceutical"): "3002",
    # Kitchen cutlery (Ch 82), not raw steel (Ch 72)
    ("kitchen", "knife"): "8211",
    ("stainless", "knife"): "8211",
    # Jeans are woven (Ch 62), not knitted (Ch 61)
    ("men", "jeans"): "6203",
    ("women", "jeans"): "6203",
    ("denim", "jeans"): "6203",
    # Canned/preserved fruit (Ch 20), not fresh (Ch 08)
    ("canned", "pineapple"): "2008",
    ("canned", "fruit"): "2008",
    ("preserved", "fruit"): "2008",
}

# ─────────────────────────────────────────────────────────────────────────────
# Chapter hints (2 digits) — product keywords → HS chapter
# Order: more specific terms first; later entries can override for same chapter
# ─────────────────────────────────────────────────────────────────────────────
CHAPTER_HINTS: dict[str, str] = {
    # Ch 01: Live animals
    "horse": "01",
    "cattle": "01",
    "pig": "01",
    "poultry": "01",
    "live animal": "01",
    # Ch 02: Meat
    "meat": "02",
    "beef": "02",
    "pork": "02",
    "lamb": "02",
    "chicken": "02",
    "mutton": "02",
    # Ch 03: Fish
    "fish": "03",
    "crab": "03",
    "shrimp": "03",
    "crustacean": "03",
    "seafood": "03",
    "crab": "03",
    "lobster": "03",
    "caviar": "03",
    # Ch 04: Dairy, eggs, honey
    "milk": "04",
    "cheese": "04",
    "butter": "04",
    "cream": "04",
    "yogurt": "04",
    "egg": "04",
    "honey": "04",
    # Ch 05: Animal products
    "wool": "05",
    "hair": "05",
    "bristle": "05",
    "gut": "05",
    "bone": "05",
    "ivory": "05",
    "coral": "05",
    "shell": "05",
    # Ch 06: Live plants
    "plant": "06",
    "bulb": "06",
    "root": "06",
    "cutting": "06",
    "flower": "06",
    "tree": "06",
    "shrub": "06",
    "orchid": "06",
    # Ch 07: Vegetables
    "potato": "07",
    "tomato": "07",
    "onion": "07",
    "garlic": "07",
    "cabbage": "07",
    "carrot": "07",
    "vegetable": "07",
    "lettuce": "07",
    "mushroom": "07",
    # Ch 08: Fruit, nuts
    "fruit": "08",
    "apple": "08",
    "orange": "08",
    "banana": "08",
    "grape": "08",
    "mango": "08",
    "durian": "08",
    "pineapple": "08",
    "nut": "08",
    "coconut": "08",
    "cashew": "08",
    "almond": "08",
    "walnut": "08",
    # Ch 09: Coffee, tea, spices
    "coffee": "09",
    "tea": "09",
    "pepper": "09",
    "spice": "09",
    "cinnamon": "09",
    "clove": "09",
    "nutmeg": "09",
    "vanilla": "09",
    "saffron": "09",
    # Ch 10: Cereals
    "wheat": "10",
    "rice": "10",
    "cereal": "10",
    "barley": "10",
    "maize": "10",
    "corn": "10",
    "oat": "10",
    "grain": "10",
    # Ch 11: Milling products
    "flour": "11",
    "meal": "11",
    "starch": "11",
    "malt": "11",
    "gluten": "11",
    # Ch 12: Seeds, grain
    "soybean": "12",
    "seed": "12",
    "oil seed": "12",
    "copra": "12",
    "linseed": "12",
    "sesame": "12",
    "sunflower": "12",
    # Ch 13: Gums, resins
    "gum": "13",
    "resin": "13",
    "lac": "13",
    "mucilage": "13",
    # Ch 14: Vegetable materials
    "bamboo": "14",
    "rattan": "14",
    "cane": "14",
    "straw": "14",
    # Ch 15: Fats, oils
    "fat": "15",
    "oil": "15",
    "lard": "15",
    "tallow": "15",
    "margarine": "15",
    "wax": "15",
    # Ch 16: Prepared meat, fish
    "sausage": "16",
    "prepared meat": "16",
    "canned meat": "16",
    "canned fish": "16",
    "caviar": "16",
    "crab meat": "16",
    # Ch 17: Sugar
    "sugar": "17",
    "molasses": "17",
    "confectionery": "17",
    "candy": "17",
    "sweet": "17",
    # Ch 18: Cocoa, chocolate
    "cocoa": "18",
    "chocolate": "18",
    "cocoa butter": "18",
    # Ch 19: Bread, pastry, biscuits
    "bread": "19",
    "biscuit": "19",
    "cookie": "19",
    "pastry": "19",
    "cake": "19",
    "wafer": "19",
    "cracker": "19",
    "cereal preparation": "19",
    # Ch 20: Preserved vegetables, fruit
    "jam": "20",
    "jelly": "20",
    "marmalade": "20",
    "preserved fruit": "20",
    "preserved vegetable": "20",
    "canned fruit": "20",
    "pickle": "20",
    "sauce": "20",
    "ketchup": "20",
    # Ch 21: Miscellaneous food
    "soup": "21",
    "yeast": "21",
    "baking powder": "21",
    "ice cream": "21",
    "food preparation": "21",
    "seasoning": "21",
    "mayonnaise": "21",
    # Ch 22: Beverages
    "wine": "22",
    "beer": "22",
    "spirit": "22",
    "alcohol": "22",
    "beverage": "22",
    "juice": "22",
    "mineral water": "22",
    "soft drink": "22",
    # Ch 23: Animal feed
    "animal feed": "23",
    "pet food": "23",
    "fodder": "23",
    "fish meal": "23",
    # Ch 24: Tobacco
    "tobacco": "24",
    "cigarette": "24",
    "cigar": "24",
    # Ch 25: Salt, sulphur
    "salt": "25",
    "sulphur": "25",
    "gypsum": "25",
    "cement": "25",
    "lime": "25",
    # Ch 26: Ores
    "ore": "26",
    "iron ore": "26",
    "copper ore": "26",
    "slag": "26",
    "ash": "26",
    # Ch 27: Mineral fuels
    "coal": "27",
    "petroleum": "27",
    "petrol": "27",
    "diesel": "27",
    "gas": "27",
    "fuel": "27",
    "bitumen": "27",
    "paraffin": "27",
    # Ch 28: Inorganic chemicals
    "chemical": "28",
    "sulphur": "28",
    "ammonia": "28",
    "acid": "28",
    "oxide": "28",
    "chloride": "28",
    # Ch 29: Organic chemicals
    "organic chemical": "29",
    "hydrocarbon": "29",
    "alcohol": "29",
    "ester": "29",
    "ether": "29",
    # Ch 30: Pharmaceutical
    "medicine": "30",
    "pharmaceutical": "30",
    "drug": "30",
    "vaccine": "30",
    "bandage": "30",
    "syringe": "30",
    "pill": "30",
    "tablet": "30",
    "capsule": "30",
    # Ch 31: Fertilizers
    "fertilizer": "31",
    "fertiliser": "31",
    "manure": "31",
    # Ch 32: Tanning, dyes
    "dye": "32",
    "tannin": "32",
    "pigment": "32",
    "paint": "32",
    "ink": "32",
    "varnish": "32",
    # Ch 33: Essential oils, perfumes
    "perfume": "33",
    "essential oil": "33",
    "cosmetic": "33",
    "toilet": "33",
    "deodorant": "33",
    "lipstick": "33",
    # Ch 34: Soaps, cosmetics
    "soap": "34",
    "detergent": "34",
    "wax": "34",
    "polish": "34",
    "candle": "34",
    # Ch 35: Albumin, starch
    "albumin": "35",
    "dextrin": "35",
    "glue": "35",
    "enzyme": "35",
    # Ch 36: Explosives
    "explosive": "36",
    "firework": "36",
    "match": "36",
    "fuse": "36",
    # Ch 37: Photo, cinematographic
    "photographic": "37",
    "film": "37",
    "camera film": "37",
    # Ch 38: Miscellaneous chemical
    "activated carbon": "38",
    "pesticide": "38",
    "herbicide": "38",
    "disinfectant": "38",
    "adhesive": "38",
    "catalyst": "38",
    # Ch 39: Plastics
    "plastic": "39",
    "polymer": "39",
    "polyethylene": "39",
    "pvc": "39",
    "acrylic": "39",
    "silicone": "39",
    "vinyl": "39",
    # Ch 40: Rubber
    "rubber": "40",
    "latex": "40",
    "tyre": "40",
    "tire": "40",
    "vulcanised": "40",
    # Ch 41: Raw hides, leather
    "raw hide": "41",
    "raw leather": "41",
    "leather hide": "41",
    "raw skin": "41",
    # Ch 42: Travel goods, handbags, leather articles
    "handbag": "42",
    "bag": "42",
    "leather goods": "42",
    "saddle": "42",
    "harness": "42",
    "travel goods": "42",
    "wallet": "42",
    "purse": "42",
    "belt": "42",
    "briefcase": "42",
    "backpack": "42",
    "luggage": "42",
    "suitcase": "42",
    "trunk": "42",
    # Ch 43: Furs
    "fur": "43",
    "fur skin": "43",
    "fur coat": "43",
    # Ch 44: Wood
    "wood": "44",
    "timber": "44",
    "lumber": "44",
    "plywood": "44",
    "particle board": "44",
    "bamboo": "44",
    "cork": "44",
    # Ch 45: Cork
    "cork": "45",
    "cork article": "45",
    # Ch 46: Straw, basket
    "basket": "46",
    "wicker": "46",
    "wickerwork": "46",
    "plaiting": "46",
    "matting": "46",
    # Ch 47: Wood pulp
    "pulp": "47",
    "wood pulp": "47",
    "waste paper": "47",
    # Ch 48: Paper
    "paper": "48",
    "cardboard": "48",
    "paperboard": "48",
    "tissue": "48",
    "kraft": "48",
    "envelope": "48",
    # Ch 49: Books, printed matter
    "book": "49",
    "newspaper": "49",
    "magazine": "49",
    "printed": "49",
    "map": "49",
    "postcard": "49",
    "calendar": "49",
    # Ch 50: Silk
    "silk": "50",
    "silk yarn": "50",
    "silk fabric": "50",
    # Ch 51: Wool
    "wool": "51",
    "woollen": "51",
    "wool fabric": "51",
    "wool yarn": "51",
    # Ch 52: Cotton
    "cotton": "52",
    "cotton yarn": "52",
    "cotton fabric": "52",
    "cotton thread": "52",
    # Ch 53: Other vegetable fibres
    "flax": "53",
    "linen": "53",
    "jute": "53",
    "hemp": "53",
    "ramie": "53",
    "sisal": "53",
    "coconut fibre": "53",
    # Ch 54: Synthetic filaments
    "synthetic": "54",
    "polyester": "54",
    "nylon": "54",
    "rayon": "54",
    "filament": "54",
    "monofilament": "54",
    # Ch 55: Synthetic staple
    "staple fibre": "55",
    "staple fiber": "55",
    "man-made fibre": "55",
    "acrylic fibre": "55",
    # Ch 56: Wadding, felt
    "wadding": "56",
    "felt": "56",
    "nonwoven": "56",
    "twine": "56",
    "rope": "56",
    "net": "56",
    # Ch 57: Carpets
    "carpet": "57",
    "rug": "57",
    "mat": "57",
    "floor covering": "57",
    # Ch 58: Special fabrics
    "lace": "58",
    "embroidery": "58",
    "tapestry": "58",
    "tulle": "58",
    "narrow fabric": "58",
    # Ch 59: Coated fabrics
    "coated fabric": "59",
    "impregnated": "59",
    "textile belt": "59",
    # Ch 60: Knitted fabrics
    "knitted fabric": "60",
    "crochet": "60",
    "knit fabric": "60",
    # Ch 61: Knitted apparel
    "t-shirt": "61",
    "shirt": "61",
    "knitted": "61",
    "cotton": "61",
    "men": "61",
    "boys": "61",
    "women": "61",
    "girls": "61",
    "jersey": "61",
    "pullover": "61",
    "sweater": "61",
    "cardigan": "61",
    "vest": "61",
    "singlet": "61",
    "underwear": "61",
    "panty": "61",
    "hosiery": "61",
    "sock": "61",
    "stocking": "61",
    "glove": "61",  # textile gloves (rubber gloves use HEADING_HINTS 4015)
    "sportswear": "61",
    "swimwear": "61",
    "track suit": "61",
    # Ch 62: Woven apparel
    "woven": "62",
    "overcoat": "62",
    "trousers": "62",
    "pants": "62",
    "jeans": "62",
    "shorts": "62",
    "skirt": "62",
    "dress": "62",
    "blouse": "62",
    "overall": "62",
    "apron": "62",
    "babies": "62",
    "baby": "62",
    "uniform": "62",
    "overall": "62",
    # Ch 63: Other textiles
    "blanket": "63",
    "bedding": "63",
    "curtain": "63",
    "tent": "63",
    "sack": "63",
    "tarpaulin": "63",
    "cleaning cloth": "63",
    # Ch 64: Footwear
    "shoe": "64",
    "footwear": "64",
    "boot": "64",
    "sandal": "64",
    "slipper": "64",
    "footwear": "64",
    # Ch 65: Headgear
    "hat": "65",
    "cap": "65",
    "headgear": "65",
    "helmet": "65",
    "wig": "65",
    # Ch 66: Umbrellas
    "umbrella": "66",
    "parasol": "66",
    "walking stick": "66",
    # Ch 67: Feather, artificial flowers
    "feather": "67",
    "artificial flower": "67",
    "quill": "67",
    "down": "67",
    # Ch 68: Stone, cement
    "stone": "68",
    "marble": "68",
    "granite": "68",
    "slate": "68",
    "cement": "68",
    "asbestos": "68",
    "mica": "68",
    # Ch 69: Ceramic
    "ceramic": "69",
    "pottery": "69",
    "porcelain": "69",
    "tile": "69",
    "brick": "69",
    "earthenware": "69",
    "sanitary": "69",
    # Ch 70: Glass
    "glass": "70",
    "glassware": "70",
    "mirror": "70",
    "glass bottle": "70",
    "lens": "70",
    # Ch 71: Pearls, precious metals
    "pearl": "71",
    "diamond": "71",
    "precious stone": "71",
    "gold": "71",
    "silver": "71",
    "platinum": "71",
    "jewellery": "71",
    "jewelry": "71",
    # Ch 72: Iron, steel
    "iron": "72",
    "steel": "72",
    "ferrous": "72",
    "ingot": "72",
    "alloy": "72",
    # Ch 73: Iron/steel articles
    "iron article": "73",
    "steel article": "73",
    "tube": "73",
    "pipe": "73",
    "nail": "73",
    "screw": "73",
    "bolt": "73",
    "nut": "73",
    "wire": "73",
    "chain": "73",
    "tank": "73",
    "container": "73",
    "stove": "73",
    "kitchenware": "73",
    # Ch 74: Copper
    "copper": "74",
    "copper article": "74",
    "brass": "74",
    "bronze": "74",
    # Ch 75: Nickel
    "nickel": "75",
    "nickel article": "75",
    # Ch 76: Aluminium
    "aluminium": "76",
    "aluminum": "76",
    "aluminium article": "76",
    # Ch 78: Lead
    "lead": "78",
    "lead article": "78",
    # Ch 79: Zinc
    "zinc": "79",
    "zinc article": "79",
    # Ch 80: Tin
    "tin": "80",
    "tin article": "80",
    # Ch 81: Other base metals
    "tungsten": "81",
    "molybdenum": "81",
    "titanium": "81",
    "tantalum": "81",
    "magnesium": "81",
    # Ch 82: Tools, cutlery
    "tool": "82",
    "cutlery": "82",
    "knife": "82",
    "fork": "82",
    "spoon": "82",
    "scissors": "82",
    "saw": "82",
    "blade": "82",
    "razor": "82",
    "spade": "82",
    "hoe": "82",
    # Ch 83: Miscellaneous metal
    "padlock": "83",
    "lock": "83",
    "hinge": "83",
    "key": "83",
    "hand tool": "83",
    "safe": "83",
    "filing": "83",
    # Ch 84: Machinery
    "machine": "84",
    "machinery": "84",
    "engine": "84",
    "pump": "84",
    "compressor": "84",
    "furnace": "84",
    "refrigerator": "84",
    "freezer": "84",
    "air conditioner": "84",
    "washing machine": "84",
    "computer": "84",
    "laptop": "84",
    "printer": "84",
    "calculator": "84",
    "typewriter": "84",
    "mill": "84",
    "lathe": "84",
    "drill": "84",
    "boiler": "84",
    "turbine": "84",
    "generator": "84",
    # Ch 85: Electrical machinery
    "electrical": "85",
    "transformer": "85",
    "battery": "85",
    "motor": "85",
    "generator": "85",
    "cable": "85",
    "wire": "85",
    "switch": "85",
    "lamp": "85",
    "bulb": "85",
    "led": "85",
    "phone": "85",
    "mobile": "85",
    "smartphone": "85",
    "headphone": "85",
    "speaker": "85",
    "microphone": "85",
    "television": "85",
    "radio": "85",
    "amplifier": "85",
    # Ch 86: Railway
    "railway": "86",
    "locomotive": "86",
    "train": "86",
    "rail": "86",
    "tram": "86",
    # Ch 87: Vehicles
    "vehicle": "87",
    "car": "87",
    "automobile": "87",
    "motorcycle": "87",
    "bicycle": "87",
    "bus": "87",
    "truck": "87",
    "lorry": "87",
    "tractor": "87",
    "trailer": "87",
    "part": "87",
    # Ch 88: Aircraft
    "aircraft": "88",
    "aeroplane": "88",
    "airplane": "88",
    "helicopter": "88",
    "drone": "88",
    "parachute": "88",
    # Ch 89: Ships, boats
    "ship": "89",
    "boat": "89",
    "vessel": "89",
    "yacht": "89",
    "ferry": "89",
    # Ch 90: Optical, medical instruments
    "optical": "90",
    "microscope": "90",
    "telescope": "90",
    "camera": "90",
    "medical": "90",
    "surgical": "90",
    "instrument": "90",
    "thermometer": "90",
    "barometer": "90",
    "survey": "90",
    "measure": "90",
    # Ch 91: Clocks, watches
    "clock": "91",
    "watch": "91",
    "timepiece": "91",
    "chronometer": "91",
    # Ch 92: Musical instruments
    "piano": "92",
    "guitar": "92",
    "violin": "92",
    "drum": "92",
    "musical": "92",
    "instrument": "92",
    "horn": "92",
    "flute": "92",
    # Ch 93: Arms, ammunition
    "arm": "93",
    "ammunition": "93",
    "gun": "93",
    "rifle": "93",
    "pistol": "93",
    "revolver": "93",
    "sword": "93",
    "bayonet": "93",
    # Ch 94: Furniture
    "furniture": "94",
    "chair": "94",
    "table": "94",
    "desk": "94",
    "bed": "94",
    "cabinet": "94",
    "mattress": "94",
    "lamp": "94",
    "lighting": "94",
    "sign": "94",
    "prefabricated": "94",
    # Ch 95: Toys, games
    "toy": "95",
    "game": "95",
    "puzzle": "95",
    "doll": "95",
    "model": "95",
    "video game": "95",
    "sport": "95",
    "bicycle": "95",
    "inflatable": "95",
    # Ch 96: Miscellaneous
    "pen": "96",
    "pencil": "96",
    "brush": "96",
    "comb": "96",
    "cigarette lighter": "96",
    "lighter": "96",
    "cigarette case": "96",
    "umbrella": "96",
    "walking stick": "96",
    "button": "96",
    "slide fastener": "96",
    "zipper": "96",
    "pipette": "96",
    "statuette": "96",
    # Ch 97: Art, antiques
    "painting": "97",
    "antique": "97",
    "art": "97",
    "collection": "97",
    "stamp": "97",
}
